def game_dict():
    return {
        "home": {
            "team_name": "Cleveland Cavaliers",
            "colors": ["Wine", "Gold"],
            "players": [
                {
                    "name": "LeBron James",
                    "number": 23,
                    "position": "Small Forward",
                    "points_per_game": 25.0,
                    "rebounds_per_game": 7.9,
                    "assists_per_game": 7.9,
                    "steals_per_game": 1.4,
                    "blocks_per_game": 0.6,
                    "career_points": 35203,
                    "age": 36,
                    "height_inches": 80,
                    "shoe_brand": "Nike",
                },
                {
                    "name": "Kevin Durant",
                    "number": 7,
                    "position": "Small Forward",
                    "points_per_game": 27.0,
                    "rebounds_per_game": 7.1,
                    "assists_per_game": 4.1,
                    "steals_per_game": 1.1,
                    "blocks_per_game": 1.1,
                    "career_points": 23341,
                    "age": 33,
                    "height_inches": 81,
                    "shoe_brand": "Nike",
                },
                {
                    "name": "Stephen Curry",
                    "number": 30,
                    "position": "Point Guard",
                    "points_per_game": 24.2,
                    "rebounds_per_game": 4.5,
                    "assists_per_game": 6.5,
                    "steals_per_game": 1.2,
                    "blocks_per_game": 0.2,
                    "career_points": 19268,
                    "age": 33,
                    "height_inches": 74,
                    "shoe_brand": "Under Armour",
                },
                {
                    "name": "Bam Adebayo",
                    "number": 13,
                    "position": "Center",
                    "points_per_game": 18.7,
                    "rebounds_per_game": 9.0,
                    "assists_per_game": 5.4,
                    "steals_per_game": 1.0,
                    "blocks_per_game": 1.1,
                    "career_points": 3261,
                    "age": 24,
                    "height_inches": 82,
                    "shoe_brand": "Nike",
                },
                {
                    "name": "Jarrett Allen",
                    "number": 31,
                    "position": "Center",
                    "points_per_game": 16.1,
                    "rebounds_per_game": 10.8,
                    "assists_per_game": 1.6,
                    "steals_per_game": 0.8,
                    "blocks_per_game": 1.3,
                    "career_points": 3945,
                    "age": 24,
                    "height_inches": 82,
                    "shoe_brand": "Nike",
                },
                {
                    "name": "Darius Garland",
                    "number": 10,
                    "position": "Point Guard",
                    "points_per_game": 21.7,
                    "rebounds_per_game": 3.3,
                    "assists_per_game": 8.6,
                    "steals_per_game": 1.3,
                    "blocks_per_game": 0.1,
                    "career_points": 3142,
                    "age": 22,
                    "height_inches": 73,
                    "shoe_brand": "Nike",
                },
                {
                    "name": "Evan Mobley",
                    "number": 4,
                    "position": "Center",
                    "points_per_game": 15.0,
                    "rebounds_per_game": 8.3,
                    "assists_per_game": 2.5,
                    "steals_per_game": 0.8,
                    "blocks_per_game": 1.7,
                    "career_points": 1034,
                    "age": 21,
                    "height_inches": 83,
                    "shoe_brand": "Adidas",
                },
                {
                    "name": "Kevin Love",
                    "number": 0,
                    "position": "Power Forward",
                    "points_per_game": 13.6,
                    "rebounds_per_game": 7.2,
                    "assists_per_game": 2.2,
                    "steals_per_game": 0.4,
                    "blocks_per_game": 0.2,
                    "career_points": 14305,
                    "age": 34,
                    "height_inches": 80,
                    "shoe_brand": "Nike",
                },
                {
                    "name": "Isaac Okoro",
                    "number": 35,
                    "position": "Small Forward",
                    "points_per_game": 8.8,
                    "rebounds_per_game": 3.0,
                    "assists_per_game": 1.8,
                    "steals_per_game": 0.8,
                    "blocks_per_game": 0.3,
                    "career_points": 1234,
                    "age": 21,
                    "height_inches": 77,
                    "shoe_brand": "Nike",
                },
                {
                    "name": "Ricky Rubio",
                    "number": 99,
                    "position": "Point Guard",
                    "points_per_game": 13.1,
                    "rebounds_per_game": 4.1,
                    "assists_per_game": 6.6,
                    "steals_per_game": 1.4,
                    "blocks_per_game": 0.2,
                    "career_points": 7399,
                    "age": 31,
                    "height_inches": 74,
                    "shoe_brand": "Adidas",
                },
            ],
            "coach": "John Doe",
            "arena": "Cleveland Arena",
        },
            
        "away": {
            "team_name": "Washington Wizards",
            "colors": ["Red", "White", "Navy Blue"],
            "players": [
                # Include the Washington Wizards' players here if needed.
            ],
            "coach": "Jane Smith",
            "arena": "Washington Arena",
        }
    }
